### ISSUE TITLE
DATABASE_USER keyerror

### ISSUE THREAD

**Issue by rsingh2083** [GraphtyLove/Face-recognition-project#21]
Hi buddy,

Im getting this error while running python3 app.py

```
Traceback (most recent call last):
  File "app.py", line 21, in <module>
    DATABASE_USER = os.environ['face_recog']
  File "/home/anaconda3/lib/python3.7/os.py", line 678, in __getitem__
    raise KeyError(key) from None
KeyError: 'face-recog'
```

**Comment by GraphtyLove** [comment]
It's because this is an environment variable. You have to set it in your system according to your DB user.

**Comment by rsingh2083** [comment]
@GraphtyLove thanks buddy. Just one minor final issue left. Can you please help on that too. Ive raised a new issue, please have a look
