### ISSUE TITLE
What is the number of people it can support

### ISSUE THREAD

**Issue by iam-rocketman** [GraphtyLove/Face-recognition-project#25]
I am planning to set up this is my university, what are the maximum faces it can support(we have about 5000 students)

**Comment by GraphtyLove** [comment]
Well, it all depends on the server you use. If you use let's say 40 cameras that request the same server every 2 seconds, well you will need to scale up the server. 

The system itself doesn't have limits but the way you will deploy it, access the data,... Will need to be adapted depending on your usage. Also, I really advise you to fully read the code and to see what has to be optimized. I wrote it in a week during my studies, it totally not production-ready as it is. Images should be resized and optimized, the back has to be wrapped with more try/except with specific exceptions,....

Good luck! And if you need any help, feel free to reach me :)
